server:
  port : 8080
  servlet:
    context-path: /api
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
  datasource:
    platform: mysql
    username: admin #Note: do not change this!
    password: password
    url: jdbc:mysql://34.125.218.39:3306/RoadTrip #or this
    driver-class-name: com.mysql.cj.jdbc.Driver